### PR TITLE
fix: missing undefined check

### LINKED ISSUE #1874: Comment helpers break SSR
https://github.com/busyorg/busy/blob/be16c359977935fe02a7490f69f75c71f0e0ae03/src/client/helpers/commentHelpers.js#L17

### LINKED ISSUE #1885: Bug: Busy.org/staging.busy.org vote slider is not working when post link redirected from third party website
#### Expected behavior

We can generally enable vote slider and can set a default vote percentage from setting of busy.org/staging.busy.org And at the time of vote, when we click on like button, the slider appear with that percentage which we set in the setting
#### Actual behavior

I saw a busy.org's post link on facebook and cchecked the post, But when i clicked on like button to upvote the post  the slider appeared with 100% vote percentage. Seems busy.org default vote percentage setting is not working when we redirect from any third party website.

#### How to reproduce
- Firstly set a default vote percentage on busy.org/staging.busy.org setting

- Now check this post for busy- https://busy.org/@tuhin786/sunday-20-may-daily-steem-and-steemit-updates-news-no-of-post-32 and following for staging.busy.org- https://staging.busy.org/@rosatravels/flying-over-the-beautiful-land-of-cappadocia-or

- Now scroll down and click on the link button

- You will see that though you have set on a specific percentage, but the slider is still on 100%

* Browser version: Google Chrome Version 66.0.3359.181 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug
https://youtu.be/qKHIpRlY-Iw

In case of staging.busy.org
https://youtu.be/PUxDaS-fDcU

### PR DESCRIPTION
**Pull request by Sekhmet**
Fixes #1874 
Fixes #1885

### Changes

* Check if window exists

### Test plan

* [x] Go to: https://busy-master-pr-1876.herokuapp.com/@hellosteem/2zebvb-test/#@emergedinsteem/re-hellosteem-2zebvb-test-20180518t213245298z
* [x] SSR should work.

### CODE REVIEW

File: src/client/helpers/commentHelpers.js [hunk 1]
```diff
@@ -14,6 +14,10 @@ function getCommentAnchor(comment) {
  * @returns the comment linked or null if not found
  */
 export function getLinkedComment(comments = []) {
+  if (typeof window === 'undefined') {
```
Comment (jm90m) [inline src/client/helpers/commentHelpers.js]: nit - might be good to use `_.isUndefined(window)` so code `if window is undefined` ....
