### PR TITLE
Fix scroll to comment behaviour

### LINKED ISSUE #821: Comment form should be focused and shown visibly after clicking the comment icon in post
comments-focus

#### Expected behavior

Comment form is focused and visible.

#### Actual behavior

Comment form is focused but it may be pushed too far up and hidden.

#### How to reproduce

1. Open a post from `/trending`. (Any post with more comments)
2. Scroll down to comment icon. (Not that far so you won't see comment form.)
3. Click the comment icon.

* Browser: Chrome 61.0.3163.100
* Operating system: Windows 10

### PR DESCRIPTION
**Pull request by karthik-awebon**
Fixes #821
Changes:
- In Button.js scrollIntoView function properties are changed
- 
-

### CODE REVIEW

File: src/components/Comments/CommentForm.js [hunk 1]
```diff
@@ -51,8 +53,8 @@ class CommentForm extends React.Component {
   }
 
   componentWillReceiveProps(nextProps) {
-    if (!nextProps.isLoading) {
-      this.setState({ inputValue: nextProps.inputValue || '' });
+    if ((!nextProps.isLoading && nextProps.inputValue !== '') || nextProps.commentSubmitted) {
```
Comment (Sekhmet) [inline src/components/Comments/CommentForm.js]: Looks like some leftover code from another PR

File: src/components/StoryFooter/Buttons.js [hunk 2]
```diff
@@ -85,8 +85,7 @@ export default class Buttons extends React.Component {
   handleCommentClick = () => {
     const form = document.getElementById('commentFormInput');
     if (form) {
-      form.scrollIntoView(true);
-      document.body.scrollTop -= 200;
+      form.scrollIntoView({ behavior: 'instant', block: 'center', inline: 'start' });
```
Comment (Sekhmet) [inline src/components/StoryFooter/Buttons.js]: Problem with using `scrollIntoViewOptions` is that it's experimental technology and not yet widely supported:
image
We shouldn't be using it as it might break things for many users.

**Comment by karthik-awebon** [comment]
@Sekhmet implemented the scroll using [react-scrol](https://www.npmjs.com/package/react-scroll)l library. Can you please review the code.

**Comment by jm90m** [comment]
Is this working for anyone? clicking the comments icon does nothing for me...

pr-1083-comments-button-not-working

**Comment by jm90m** [comment]
Looks like when I'm logged in it focuses on input but doesn't scroll down and center it

busy-1083-pr-comment-form-focus

**Comment by karthik-awebon** [comment]
@jm90m did your cleared your browser cache and tested that? @bonustrack did you tested it, is it working for you?

**Comment by jm90m** [comment]
yes this works for me for some screen sizes, but for large screen sizes it doesn't. But could just be me, I'm on a 27" monitor.

**Comment by Sekhmet** [comment]
It seems to work for me.

**Comment by karthik-awebon** [comment]
@Sekhmet Can you please approve this pull request.

**Comment by bonustrack** [comment]
@karthik-awebon i'm not sure what if it's the intended behavior but for me i'm not always able to see the full comment form when i click in comment icon, see:
test

Also we the base branch of this PR should be `master`.

**Comment by bonustrack** [comment]
I'm interested to know if this PR solve the issue for @espoem also because it's not an issue that i have on current busy.org version, you can test here: https://busy-master-pr-1083.herokuapp.com/

**Comment by espoem** [comment]
I think this solves the issue I reported. I give comparison for what I can see.

- version busy.org

busy-comment

- version https://busy-master-pr-1083.herokuapp.com/

busy-comment-test

**Comment by jm90m** [comment]
Does this work for you @bonustrack ? We can merge once you approve it.

**Comment by bonustrack** [comment]
You can squash merge it @karthik-awebon
