### PR TITLE
Fix SSR Renderer on stable

### LINKED ISSUE #1352: Some post are breaking the layout
image
It seem related to this post: https://steemdb.com/bitshares/@heiditravels/blockchain-generations-from-bitcoin-to-smart-contracts-and-graphene/data
As the console lead to an error for this post on the var `window.__PRELOADED_STATE__ `
image

### PR DESCRIPTION
**Pull request by jm90m**
Fixes #1352

### CODE REVIEW

File: src/server/renderers/ssrRenderer.js [hunk 1]
```diff
@@ -12,7 +12,9 @@ export default function renderSsrPage(store, html, template) {
       `<script>
         // WARNING: See the following for security issues around embedding JSON in HTML:
         // http://redux.js.org/docs/recipes/ServerRendering.html#security-considerations
-        window.__PRELOADED_STATE__ = ${JSON.stringify(preloadedState.replace(/\u2028/g, '\n')).replace(/</g, '\\u003c')}
+        window.__PRELOADED_STATE__ = ${JSON.stringify(preloadedState)
+    .replace(/\u2028/g, '\\n')
```
Comment (bonustrack) [inline src/server/renderers/ssrRenderer.js]: The intend is wrong, can you fix it?
