### PR TITLE
fix relative url

### LINKED ISSUE #2105: Relative links get prefixed by "https://"
#### Expected behavior

A relative link shouldn't get prefixed and instead bring you to a page on Busy.

#### Actual behavior

Any relative link gets prefixed by "https://", turning it into a dead link (looking like https:///relative).

#### How to reproduce

Write a relative link in the post editor and try clicking on it in the preview.

Here is an example of a relative link turning into a dead one: 
https://busy.org/@timcliff/re-c1udadan0x-re-steemitblog-tracking-smt-development-progress-20180821t154624322z

I believe this bug has been introduced in the commit 22cbd06 related to the issue #2092.

### PR DESCRIPTION
**Pull request by economicstudio**
Fixes #2105

### Changes

* Fix the relative url issues. "/@user" and "/@user/permlink" now work!

### Test plan

* [ ] https://busy.org/@blockchainstudio/utopian-bug-hunting

I made a post for testing. It has various links for testing.

### CODE REVIEW

**Comment by anpigon** [comment]
good fixed. I nedd it.

File: src/client/vendor/steemitHtmlReady.js [hunk 1]
```diff
@@ -122,9 +122,8 @@ function link(state, child) {
     state.links.add(url);
     if (state.mutate) {
       // If this link is not relative, http, or https -- add https.
-      if (!/^[\w.-]+:(\/\/)?/.test(url)) {
-        child.setAttribute('href', `https://${url}`);
-      }
+      if (/^\//.test(url)) child.setAttribute('href', `https://busy.org${url}`);
```
Comment (Sekhmet) [inline src/client/vendor/steemitHtmlReady.js]: We shouldn't use hardcoded `https://busy.org` URL. It won't work on localhost, preview apps, beta version and forks.

Comment (economicstudio) [reply src/client/vendor/steemitHtmlReady.js]: Thanks for your comment. I've removed it now.
