### PR TITLE
Fixes post reading time large focus area issue

### LINKED ISSUE #1107: Time to read has large area of focus
If you open a post, you will see a time to read estimation. If you also hover over the text, the tooltip with the number of words will show. The problem is that the tooltip is shown even if you hover over the middle part between time and the estimated time to read.

### Expected behaviour

The tooltip should show only if the user hover over the text.

### Steps to reproduce

1. Open a post
2. Hover over the date and move to the estimated read time

- Browser: Chrome
- OS: WIndows 10

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@espoem/time-to-read-has-large-area-of-focus">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

### PR DESCRIPTION
**Pull request by sirrius-a-b**
Fixes #1107 .

Changes:
- moved the `CommentFooter__bullet` outside of the `Tooltip`
- made small CSS changes to keep the existing style given the above change

### CODE REVIEW

File: src/components/Story/StoryFull.js [hunk 1]
```diff
@@ -312,26 +312,29 @@ class StoryFull extends React.Component {
               </span>
             </Tooltip>
             { Math.ceil(readingTime(post.body).minutes) > 1 &&
-              <Tooltip
-                title={
-                  <span>
+              <div className="inline-block">
+                <span className="CommentFooter__bullet" />
```
Comment (bonustrack) [inline src/components/Story/StoryFull.js]: I think we should change the class name. The name `CommentFooter_..` is not relevant here.

File: src/components/Story/StoryFull.js [hunk 2]
```diff
@@ -312,26 +312,29 @@ class StoryFull extends React.Component {
               </span>
             </Tooltip>
             { Math.ceil(readingTime(post.body).minutes) > 1 &&
-              <Tooltip
-                title={
-                  <span>
+              <div className="inline-block">
```
Comment (bonustrack) [inline src/components/Story/StoryFull.js]: Why not using `<span>` instead of `<div className="inline-block">` ?

**Comment by sirrius-a-b** [comment]
I made the above requested changes.

**Comment by jm90m** [comment]
Looks like this has conflicts, please resolve it then we can retest and merge it :) thanks again!

**Comment by sirrius-a-b** [comment]
Fixed, please retest  :)
