### PR TITLE
fix: update mention detection from condenser

### LINKED ISSUE #1978: Bug: Staging.busy.org cuts off Url path after @username
#### Expected behavior

Generally we can see full link of steem based front end links on staging.busy.org and can also click on it.
as like below picture-
screenshot_24
This screenshot is from busy.org

#### Actual behavior

On staging.busy.org it is cutting off the link path after the username of all steem front end. And we can not go to that link by clicking on it.

#### How to reproduce

- Login to staging.busy.org. If you are on busy.org then mark "Use Busy beta" option from setting.

- Now take post link from steemit or busy or any other front end. Or you can test with this link `https://steemit.com/test/@sourovafrin/68hxar-test`

- Now do a post or comment by this link.

- You will see the link is only clickable upto username. The rest path is unclickable.

* Browser version: Chrome Version 67.0.3396.79 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug
candidagilefirebelliedtoad-size_restricted

if the gif size is small to understand then check it [here](https://gfycat.com/gifs/detail/CandidAgileFirebelliedtoad)

### PR DESCRIPTION
**Pull request by Sekhmet**
Fixes #1978 

### Changes

* Update mention detection logic from: https://github.com/steemit/condenser/blob/master/src/shared/HtmlReady.js#L272-L290

### Test plan

Explain how to test changes you made.

* [x] Go to: https://busy-master-pr-1985.herokuapp.com/@hellosteem/sqfae-test
* [x] Link and mentions should render properly.

### CODE REVIEW

File: src/client/vendor/steemitHtmlReady.js [hunk 1]
```diff
@@ -226,15 +226,25 @@ function linkify(content, mutate, hashtags, usertags, images, links) {
...
-    const userLower = user2.toLowerCase();
-    const valid = validateAccountName(userLower) == null;
-    if (valid && usertags) usertags.add(userLower);
-    if (!mutate) return user;
-    return space + (valid ? `<a href="/@${userLower}">@${user2}</a>` : `@${user2}`);
-  });
+  // Cribbed from https://github.com/twitter/twitter-text/blob/v1.14.7/js/twitter-text.js#L90
+  // https://github.com/steemit/condenser/blob/7c588536d2568a554391ea1edaa656c636c5a890/src/shared/HtmlReady.js#L272-L290
+  content = content.replace(
+    /(^|[^a-zA-Z0-9_!#$%&*@＠\/]|(^|[^a-zA-Z0-9_+~.-\/#]))[@＠]([a-z][-\.a-z\d]+[a-z\d])/gi,
```
Comment (jm90m) [inline src/client/vendor/steemitHtmlReady.js]: I'm going to assume that whoever wrote this regex in condenser is correct. lol.
