### PR TITLE
Display Login Modal for unlogged users when they try to Like/Upvote/Save/etc...

### LINKED ISSUE #315: Direct the logged out users to the login page when they hit Comment
Users can start writing a comment without being logged in, but they cannot submit it, which may cause frustration.

### LINKED ISSUE #469: Show alert when clicking on button action: "need to login" to Like/Upvote/Bookmark
Do same like we did with the Comment button, but with all other actions which require login (Like/Dislike/Bookmark-hide)
image

### LINKED ISSUE #803: Implementation details on handling unauthenticated user actions
I feel like we could use redux middleware for this, that will pass data about required permissions per action in metadata (so whether user needs to be logged in or not) and if user doesn't have required permissions we could trigger global modal with payload that we could use to handle this action later after signing in.

We could add `meta.authAction = true` to action to notify our middleware that this action should be handled.

Middleware could behave like this.

For **authenticated** user:
1. Action is dispatched.
2. Middleware checks if action requires authentication and if user is authenticated.
3. Action continues normally.

For **unauthenticated** user:
1. Action is dispatched.
2. Middleware checks if action requires authentication and if user is authenticated.
3. Middleware opens modal with payload based on action dispatched.
4. Modal can cancel action or redirect user to SteemConnect (with redirect URL with parameters based on action) depending on user's choice.
5. User logs in on SteemConnect and get's redirected back to Busy.
6. We retrieve action from URL.
7. Continue action execution.

We could use this to handle different action permissions requirements (instead of `authenticated/unauthenticated` we could have actions that require `none`, `posting`, `active`, `master` or `memo` permissions). If user logged in with key that has insufficient permissions to perform such action we could request upgrading access.

What do you think?

### LINKED ISSUE #1226: Upvoting post while unlogged out, displays voting slider with NAN
#### Expected behavior
Should either display modal to request user to login or take user to login page directly

#### Actual behavior
clicking-on-vote-for-unlogged

#### How to reproduce

* Browser: Chrome
* Operating system: Max OSX El Capitan 

#### Related Issues
https://github.com/busyorg/busy/issues/469
https://github.com/busyorg/busy/issues/315
https://github.com/busyorg/busy/issues/803

### PR DESCRIPTION
**Pull request by jm90m**
Fixes #1226
Fixes #469
Fixes #315
Fixes #803

screen shot 2017-12-21 at 2 24 38 pm

Changes:
- Create LoginModal Component
- Add authenticated checks to Story/Comments Footer Buttons
- Add authenticated checks to FollowButton
- Add authenticated Story Preview component (by passing authenticated prop from Feed)

### CODE REVIEW

**Comment by jm90m** [comment]
as discussed with @Sekhmet, just updated everything to use a HoC `withAuthActions`

Let me know if i did this right @Sekhmet :rofl:

**Comment by bonustrack** [comment]
Can we have bigger buttons like the one in reblog?
image

**Comment by jm90m** [comment]
@bonustrack  yeah we can let me update it to look like reblog buttons

**Comment by jm90m** [comment]
@bonustrack just pushed, made it larger

File: src/client/components/LoginModal.js [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+          <span className="LoginModal__login-title">
+            <FormattedMessage id="login_to_busy" defaultMessage="Login to Busy" />
+          </span>
+          <span className="LoginModal__login-description">
+            <FormattedMessage
+              id="login_modal_description"
+              defaultMessage="Login with your Steem account using SteemConnect to enjoy Busy at 100%"
+            />
+          </span>
+          <span role="presentation" className="LoginModal__login-button" onClick={this.handleLogin}>
```
Comment (Sekhmet) [inline src/client/components/LoginModal.js]: Can we use `ahref` for that? It would make it more accessible.

File: src/client/components/StoryFooter/Buttons.js [hunk 2]
```diff
@@ -34,79 +37,100 @@ export default class Buttons extends React.Component {
...
-  handleCloseReactions = () =>
+  handleCloseReactions() {
     this.setState({
       reactionsModalVisible: false,
     });
+  }
 
-  handleCommentClick = () => {
+  // eslint-disable-next-line class-methods-use-this
+  handleCommentClick() {
```
Comment (Sekhmet) [inline src/client/components/StoryFooter/Buttons.js]: I would rather make it static method than disable the rule.

Comment (jm90m) [reply src/client/components/StoryFooter/Buttons.js]: sure we can make it a static method

File: src/client/components/LoginModal.js (hunk 1 above)
Comment (jm90m) [reply src/client/components/LoginModal.js]: yeah will change now

**Comment by jm90m** [comment]
@Sekhmet prettier runs every time i save a file so it removes the parens, but ill add it back if you think its helpful

**Comment by jm90m** [comment]
@Sekhmet done, re-added parents & made requested changes, i think i got them all lmk if im missing some
